/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MoviesIndexRouteImport } from './routes/movies/index'
import { Route as CharactersIndexRouteImport } from './routes/characters/index'
import { Route as MoviesMovieIdRouteImport } from './routes/movies/$movieId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MoviesIndexRoute = MoviesIndexRouteImport.update({
  id: '/movies/',
  path: '/movies/',
  getParentRoute: () => rootRouteImport,
} as any)
const CharactersIndexRoute = CharactersIndexRouteImport.update({
  id: '/characters/',
  path: '/characters/',
  getParentRoute: () => rootRouteImport,
} as any)
const MoviesMovieIdRoute = MoviesMovieIdRouteImport.update({
  id: '/movies/$movieId',
  path: '/movies/$movieId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/movies/$movieId': typeof MoviesMovieIdRoute
  '/characters': typeof CharactersIndexRoute
  '/movies': typeof MoviesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/movies/$movieId': typeof MoviesMovieIdRoute
  '/characters': typeof CharactersIndexRoute
  '/movies': typeof MoviesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/movies/$movieId': typeof MoviesMovieIdRoute
  '/characters/': typeof CharactersIndexRoute
  '/movies/': typeof MoviesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/movies/$movieId' | '/characters' | '/movies'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/movies/$movieId' | '/characters' | '/movies'
  id: '__root__' | '/' | '/movies/$movieId' | '/characters/' | '/movies/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MoviesMovieIdRoute: typeof MoviesMovieIdRoute
  CharactersIndexRoute: typeof CharactersIndexRoute
  MoviesIndexRoute: typeof MoviesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movies/': {
      id: '/movies/'
      path: '/movies'
      fullPath: '/movies'
      preLoaderRoute: typeof MoviesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/characters/': {
      id: '/characters/'
      path: '/characters'
      fullPath: '/characters'
      preLoaderRoute: typeof CharactersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movies/$movieId': {
      id: '/movies/$movieId'
      path: '/movies/$movieId'
      fullPath: '/movies/$movieId'
      preLoaderRoute: typeof MoviesMovieIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MoviesMovieIdRoute: MoviesMovieIdRoute,
  CharactersIndexRoute: CharactersIndexRoute,
  MoviesIndexRoute: MoviesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
